property_repository:
  type: MemoryPropertyRepo

user_repository:
  type: MemoryUserRepo

directions_repository:
  type: MemoryDirectionsRepo

directions_service:
  type: GoogleDirections
  api-key: CHANGEME
  work-location:
    latitude: 51.0
    longitude: 1.0
  search-area:
    northEast:
      lat: 51.1
      lng: 0.03
    southWest:
      lat: 51.0
      lng: -0.03
    latsamples: 100
    lngsamples: 100

scrape:
  # Scrapy settings for crib project
  #
  # You can find more settings consulting the documentation:
  #
  #     https://doc.scrapy.org/en/latest/topics/settings.html
  #     https://doc.scrapy.org/en/latest/topics/downloader-middleware.html
  #     https://doc.scrapy.org/en/latest/topics/spider-middleware.html
  #
  # The settings are converted to YAML.
  BOT_NAME: crib
  SPIDER_MODULES:
    - crib.scraper.spiders
  NEWSPIDER_MODULE: crib.scraper.spiders

  # Crawl responsibly by identifying yourself (and your website) on the user-agent
  USER_AGENT: "crib (+https://storax.github.io)"

  # Obey robots.txt rules
  ROBOTSTXT_OBEY: true

  # Configure maximum concurrent requests performed by Scrapy (default: 16)
  CONCURRENT_REQUESTS: 4

  # Configure a delay for requests for the same website (default: 0)
  # See https://doc.scrapy.org/en/latest/topics/settings.html#download-delay
  # See also autothrottle settings and docs
  DOWNLOAD_DELAY: 1
  # The download delay setting will honor only one of:
  # CONCURRENT_REQUESTS_PER_DOMAIN: 16
  # CONCURRENT_REQUESTS_PER_IP: 16

  # Disable cookies (enabled by default)
  # COOKIES_ENABLED: false

  # Disable Telnet Console (enabled by default)
  # TELNETCONSOLE_ENABLED: false

  # Override the default request headers:
  # DEFAULT_REQUEST_HEADERS:
  #   Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8'
  #   Accept-Language: 'en'

  # Enable or disable spider middlewares
  # See https://doc.scrapy.org/en/latest/topics/spider-middleware.html
  # SPIDER_MIDDLEWARES:
  #    crib.scraper.middlewares.CribSpiderMiddleware: 543

  # Enable or disable downloader middlewares
  # See https://doc.scrapy.org/en/latest/topics/downloader-middleware.html
  DOWNLOADER_MIDDLEWARES:
    scrapy.downloadermiddlewares.httpcache.HttpCacheMiddleware: 100

  # Enable or disable extensions
  # See https://doc.scrapy.org/en/latest/topics/extensions.html
  # EXTENSIONS:
  #   scrapy.extensions.telnet.TelnetConsole: None

  # Configure item pipelines
  # See https://doc.scrapy.org/en/latest/topics/item-pipeline.html
  ITEM_PIPELINES:
     crib.scraper.pipelines.CribPipeline: 100

  # Enable and configure the AutoThrottle extension (disabled by default)
  # See https://doc.scrapy.org/en/latest/topics/autothrottle.html
  AUTOTHROTTLE_ENABLED: true
  # The initial download delay
  AUTOTHROTTLE_START_DELAY: 5
  # The maximum download delay to be set in case of high latencies
  AUTOTHROTTLE_MAX_DELAY: 60
  # The average number of requests Scrapy should be sending in parallel to
  # each remote server
  AUTOTHROTTLE_TARGET_CONCURRENCY: 2.0
  # Enable showing throttling stats for every response received:
  AUTOTHROTTLE_DEBUG: true

  # Enable and configure HTTP caching (disabled by default)
  # See https://doc.scrapy.org/en/latest/topics/downloader-middleware.html#httpcache-middleware-settings
  HTTPCACHE_ENABLED: false
  HTTPCACHE_EXPIRATION_SECS: 0
  HTTPCACHE_DIR: /media/data/heavy/crib/scrapy/httpcache
  HTTPCACHE_IGNORE_HTTP_CODES: []
  HTTPCACHE_STORAGE: scrapy.extensions.httpcache.FilesystemCacheStorage

  RIGHTMOVE_SEARCHES: []
    # - "https://www.rightmove.co.uk/property-to-rent/find.html?locationIdentifier=USERDEFINEDAREA%5E%7B%22id%22%3A4848180%7D&minBedrooms=1&maxPrice=1500&minPrice=1000&dontShow=houseShare%2Cretirement&letType=longTerm"
